language: python
python:
#   - "3.6"      # Guess we don't work on 3.6?  Not fixing it right now.
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
  - pip install tox-travis
  
script:
  - tox
  # - pytest --cov=pygmst --cov-report=term-missing

after_success:
  - coveralls